modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL="https://github.com/${project_github_repo}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${mod_id}-common.mixins.json"
[[mixins]]
config = "${mod_id}.mixins.json"