org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.caching = true
fabric.loom.multiProjectOptimisation = true

minecraft_version = 26.2
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.2
neoforge_version = 26.2.0.59

mod_id = pandalib
mod_version = 1.0.0
mod_group = dev.pandasystems

mod_name = PandaLib
mod_description = A multipurpose library with a Config API, Kotlin library support, a bit of utility code, and more.
mod_authors = The Panda Oliver
mod_license = GNU LGPLv3