name: Build

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ "versions/dev/*" ]
  pull_request:
    branches: [ "versions/dev/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload individual jars
        uses: actions/upload-artifact@v4
        with:
          name: Individual_Jars
          path: build/libs/

      - name: Merge jars
        run: ./gradlew mergeJars

      - name: Upload merged jar
        uses: actions/upload-artifact@v4
        with:
          name: Merged_Jar
          path: build/forgix/

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
