name: Build

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ "versions/dev/*" ]
  pull_request:
    branches: [ "versions/dev/*" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # Upload build outputs so downstream jobs can reuse them
      - name: Upload individual jars
        uses: actions/upload-artifact@v4
        with:
          name: Individual_Jars
          path: |
            fabric/build/libs/
            neoforge/build/libs/
            forge/build/libs/

  # Merge individual jars into a single jar
  merge-artifacts:
    name: Merge and upload merged jar
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Download individual jars
        uses: actions/download-artifact@v4
        with:
          name: Individual_Jars
          path: .

      - name: Merge jars
        run: ./gradlew mergeJars

      - name: Upload merged jar
        uses: actions/upload-artifact@v4
        with:
          name: Merged_Jar
          path: build/forgix/

  # Publish maven artifacts to GitHub Packages
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
