name: Publish

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  publish:
    name: Publish maven artifacts to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Publish to GitHub Packages
        run: ./gradlew publish